### ISSUE TITLE
sip rtproxy pass to httpd

### ISSUE THREAD

**Issue by dipenpatel235** [oskar456/rtp2httpd#1]
hello..
i am looking for solution to sip rtp data tranfer over rtp2httpd 
so using your tool how can i do that ?
can u please help me ?

Thanks

**Comment by oskar456** [comment]
Hello, this software is meant to convert multicasted UDP/RTP streams (like TV broadcast) into HTTP.

What exactly is your desired use case with SIP?

**Comment by dipenpatel235** [comment]
yes ..i am finding if it is useful for sip with rtp .
because in sip also rtp used.

thats why just asked to you if anything related

**Comment by oskar456** [comment]
Sorry, I don't understand what is your use case, how converting RTP to HTTP would help you in SIP scenario.
