### ISSUE TITLE
Can not find the output service address format

### ISSUE THREAD

**Issue by NangenX** [oskar456/rtp2httpd#3]
I have add my program information on conf
**test MUDP 224.10.10.1 5000**
and try some address and it's not working

**Comment by NangenX** [comment]
just try some formats on the vlc http://serverip:port/udp/224.10.10.1:5000, i don't know if the format is correct

**Comment by NangenX** [comment]
sorry , i have worked out, modified the conf file and change to 
**test  /udp/224.10.10.1:5000**
and use VLC play the address http://serverip:port/udp/224.10.10.1:5000

Close issue

**Comment by oskar456** [comment]
If you put a line like this into the config file:

    test MUDP 224.10.10.1 5000

then the content should be reachable on URL `http://server:port/test`

Using `http://serverip:port/udp/224.10.10.1:5000` is actually [UDPxy](http://www.udpxy.com/) compatibility mode. For using this mode you don't have to put anything into the config file as everything is already included in the URL. Hope this helps.
