### ISSUE TITLE
Can't compile under linux - configuration files missing

### ISSUE THREAD

**Issue by jlaenge** [oskar456/rtp2httpd#5]
Hi @oskar456,

I'm trying to compile the project under Ubuntu 22.04 and am having some issues following the installation instructions provided in the INSTALL file. When running `autoconf` I get fhe following error:
```
configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

When running `./configure` afterwards, I get:
```
configure: error: cannot find required auxiliary files: config.guess config.sub
```

I don't have much experience with `autoconf` so this is most likely an error on my side. Can you provide more details on how to compile the project?

Kind regards,
Jakob

**Comment by oskar456** [comment]
Hey @jlaenge, I tried to compile it on Ubuntu 22.04 without issues. 
In case you cloned the repository, it is necessary to run `autoreconf -i` before runing `./configure` - the `INSTALL` document is for [released tarballs](https://github.com/oskar456/rtp2httpd/releases/tag/v1.4) which contain configure script pregenerated.

On a fresh Ubuntu 22.04, I compiled it like this:
```
$ sudo apt install build-essential
$ wget https://github.com/oskar456/rtp2httpd/releases/download/v1.4/rtp2httpd-1.4.tar.bz2
$ tar xjvf rtp2httpd-1.4.tar.bz2 
$ cd rtp2httpd-1.4
$ ./configure 
$ make
```

**Comment by jlaenge** [comment]
Hi @oskar456,

thank you so much for the quick and detailed reply. Using the method you outlined above works for me as well.

However, cloning the project in the usual way, i.e. via
`git clone https://github.com/oskar456/rtp2httpd.git`
I still have problems compiling, even using `autoconf -i` as you mentioned, instead of `autoconf` as I did before.
It looks like some files are not checked into the repository that are present in the `rtp2httpd-1.4.tar.bz2` archive you mentioned (for example the `/src/config.h.in`). Not sure if this is intended.

Kind regards,
Jakob

**Comment by oskar456** [comment]
The proper command is `autoreconf` not `autoconf` - don't ask me why, I have no idea. :)

**Comment by jlaenge** [comment]
Right, sorry I missed that in your initial comment. That works now as well.
Thanks for clarifying!
