### ISSUE TITLE
How to set iptv interface in rtp2httpd?

### ISSUE THREAD

**Issue by pioneer604** [oskar456/rtp2httpd#6]
Hello, i want to use rtp2httpd as a replacement for udpxy, but i can't find where to set iptv interface ip.
Does rtp2httpd support relay traffic between different subnets as udpxy do? 
If rtp2httpd support relay, where can i set iptv interface ip.
can u please help me ?

**Comment by oskar456** [comment]
Which `udpxy` option are you talking about? In general you don't configure interfaces, only multicast groups. Sometimes it helps if you add a route to multicast IPv4 range `240.0.0.0/4` to the inteface you wish to receive multicast traffic from.
